### ISSUE TITLE
[Readme] Bring back Tesseract

### ISSUE THREAD

**Issue by Nought57** [TesseractNetwork/Tesseract#1]
This is the one that I am making a restart on a personal basis.
It may take time to bug fix. Also, the update frequency may decrease.
Please put it somewehre in your mind.

**Comment by caspervanneck** [comment]
@Nought57 do you need help

**Comment by caspervanneck** [comment]
?

**Comment by fuyutsuki** [comment]
@Nought57 日本人であるということを踏まえ、日本語で質問させていただきます。
packsフォルダにリソースパックのzipを入れたのですが、
> Skipped resource entry  due to directory resource packs currently unsupported

と出ました。まだ対応していないということでしょうか。

**Comment by Nought57** [comment]
@caspervanneck It is so hard to develop src by only me.
Many will be pleased if you help me.

**Comment by Nought57** [comment]
@fuyutsuki ResourcePackの関係については、開発段階でプロジェクトが中止になってしまったので、残念ながら動作しない状態でのリリースになってしまいました。今後、修正していく予定ですが、現在は私1人でプロジェクトを進めている状態なので、気長にお待ち頂けると幸いです。

**Comment by caspervanneck** [comment]
@Nought57 invite me plz zo i can help

**Comment by Nought57** [comment]
@caspervanneck I sent an invitation now.

**Comment by caspervanneck** [comment]
@Nought57 i can only pullrequest can i get full permison @Nought57

**Comment by fuyutsuki** [comment]
@Nought57 了解しました。ありがとうございます。

**Comment by Nought57** [comment]
@caspervanneck Oops, Permission changed now.

**Comment by MasterOfTheRealm** [comment]
Bring Back Tesseract!

**Comment by McGrimmi** [comment]
Invite @NFGamerMC i think he can help you too.

**Comment by NFGamerMC** [comment]
Yes, I can help with the repo, invite me

**Comment by caspervanneck** [comment]
@NFGamerMC  realy do want it i invite you if you want

**Comment by NFGamerMC** [comment]
No, we are switching to TesseractMC

**Comment by NFGamerMC** [comment]
For a better repo go [HERE](https://GitHub.com/TesseractMC/Tesseract)

**Comment by poustmal** [comment]
Take all decision for tesseract,continue all here or to NFGamerMC fork,or just rename it one of theese forks tesseract 2

**Comment by poustmal** [comment]
idk which of 2 forks is better.....

**Comment by ISRAPIL** [comment]
IT @poustmal

**Comment by NFGamerMC** [comment]
Ours is, it has a ci platform and regular updates

**Comment by TheRoyalBlock** [comment]
I sure hope that this will keep updated.

**Comment by NFGamerMC** [comment]
@TheRoyalBlock Ours is best me and @xZeroMCPE are working on @TesseractMC

Check it out and help us develop it!

**Comment by xZeroMCPE** [comment]
@NFGamerMC We will return back to the original repo, @NFGamerMC will own it and will try to keep it alive!

**Comment by TheRoyalBlock** [comment]
Sounds nice!
Side note: @xZeroMCPE Do you and @AppleDevelops still have a grudge against me?

**Comment by xZeroMCPE** [comment]
Nope

**Comment by TheRoyalBlock** [comment]
Nope to the unban, or nope to the grudge? (I'm hoping its the latter)

**Comment by xZeroMCPE** [comment]
both
