### ISSUE TITLE
We have moved!

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractNetwork/Tesseract#10]
Me and the owner have decided to merge here, at https://github.com/TesseractMC/Tesseract

Please update read me so we can all work on one repo

**Comment by Nought57** [comment]
Please do no spam.

**Comment by NFGamerMC** [comment]
Sorry, but please update the repo. We are moving to TesseractMC, ask the owner of the repo

**Comment by NFGamerMC** [comment]
Check with him/her

**Comment by McGrimmi** [comment]
@NFGamerMC I think owner is @Nought57

**Comment by NFGamerMC** [comment]
Ohhh, still the new one has over 80 commits and a CI with auto build phars. It is also more full
