### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractNetwork/Tesseract#13]
What for? We returned the standard tesseract repository

**Comment by caspervanneck** [comment]
no i dont think so i ask it i must create a pull request @ISRAPIL

**Comment by ISRAPIL** [comment]
What? @caspervanneck

**Comment by QueryPE** [comment]
@Nought57 are we gonna contiune on here or shall we go to the original Tesseract?

**Comment by Nought57** [comment]
@ISRAPIL Because Tesseract branched out. They wanted to move together.
However, I think that it will not work well for people with different policies.
The leader ceased to exist and the cohesion disappeared.
Sometimes there is a discrepancy between developers' opinions and reputation is getting worse.
I think that I should value the opinions of users.
I don't know why original tesseract recovered.
I think there is a deep reason also for the leader to cancel the plan.
I wonder whether it was easy to return it to easy.

@QueryPE  I'm going to continue here.
I would like to emphasize ease of use.
I want to reduce bugs more than adding extra functions.
Original Tesseract abandoned some functions.
The useful things users wanted have also been reduced.
but, This is unavoidable for weight saving.
I will also continue to commit to the original tesseract.
Since the policy is different, I will commit accordingly.

**Comment by QueryPE** [comment]
@Nought57 honestly I like they way you think tbh :)

should we remain under the Tesseract Name or change it because changing it seems like a good options to separate us from the other one, or we could remain under this name I do not mind either way

**Comment by QueryPE** [comment]
@Nought57 also what should I work on, I'm not a very skilled developer I'm a kinda new developer but I do know the basics of php and I have made plugins in the past and I have worked on genisys under a different name that I no longer associate myself with but I can help anyway you want

**Comment by Nought57** [comment]
@QueryPE  As you said, It may be good to rename it and make it a new one.
I have done src development for quite some time.
Just like you, I was working with a different name.
If you include Tesseract, I was involved in four src developments.

**Comment by QueryPE** [comment]
@Nought57 I think we should rename this becuase if we set ourselves apart from them we can take this software in a better direction

**Comment by Nought57** [comment]
@QueryPE Then, I have to decide the name of src.
There are plants such as EXTRA (src name) in the plan canceled in the past.

**Comment by ISRAPIL** [comment]
Let's change the name to ExtraPE or ExtraCorePE @QueryPE @Nought57 @MCPEGamerJPatGitHub

**Comment by QueryPE** [comment]
@Nought57 I kinda like that

**Comment by Nought57** [comment]
Create New?? Change?? I think New Org.

**Comment by ISRAPIL** [comment]
I do not like NFGamerMC , he's very stupid boy, to a maximum of 12-13 years

**Comment by ISRAPIL** [comment]
Create @Nought57

**Comment by Nought57** [comment]
The forum was listed as spam man.

**Comment by QueryPE** [comment]
Create a new Org under ExtraCoreTeam or maybe ExtraPE and invite us :)

**Comment by ISRAPIL** [comment]
How can I contact you? @Nought57

**Comment by QueryPE** [comment]
also link the new repository in this one in case anyone wants that info :)

**Comment by Nought57** [comment]
Did you see the web? There was a name of Remotevase.

**Comment by ISRAPIL** [comment]
What? @Nought57

**Comment by QueryPE** [comment]
wait what about him?

**Comment by caspervanneck** [comment]
@Nought57 what

**Comment by Nought57** [comment]
Tesseract Web Site.

**Comment by caspervanneck** [comment]
aaa

**Comment by Nought57** [comment]
Create by remotevase

**Comment by QueryPE** [comment]
He used a template I think :)

**Comment by ISRAPIL** [comment]
Give link @QueryPE @Nought57

**Comment by ISRAPIL** [comment]
@Nought57 give link, pls

**Comment by caspervanneck** [comment]
wtf © TesseractTeam 2017. Website made by TheRoyalBlock and remotevase. All Rights Reserved.

**Comment by caspervanneck** [comment]
@ISRAPIL here http://tesseractteam.ml

**Comment by Nought57** [comment]
@ISRAPIL @QueryPE 
ExtraPE/ExtraPE?? or  ExtraPE/Extra??

**Comment by ISRAPIL** [comment]
I can do better ... @QueryPE @Nought57

**Comment by ISRAPIL** [comment]
ExtraCorePE @Nought57

**Comment by QueryPE** [comment]
@ISRAPIL yus I like that

**Comment by Nought57** [comment]
ExtraCorePE/ExtraPE

**Comment by ISRAPIL** [comment]
ExtraCorePE

**Comment by Nought57** [comment]
Ora/Repo

**Comment by ISRAPIL** [comment]
What? :) @Nought57

**Comment by ISRAPIL** [comment]
Yes

**Comment by Nought57** [comment]
Yeah

**Comment by QueryPE** [comment]
Invite me :) when u create it

**Comment by ISRAPIL** [comment]
need to create a chat

**Comment by QueryPE** [comment]
we can use gitter

**Comment by Nought57** [comment]
https://github.com/ExtraCorePE/ExtraCorePE

**Comment by ISRAPIL** [comment]
Nice

**Comment by caspervanneck** [comment]
@Nought57 invite me (:
