### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by MCPEGamerJPatGitHub** [TesseractNetwork/Tesseract#3]
Here is a list of things to be implemented, and I will be happy to work on some of them
-Texture packs
-New world generator
-Fixed beacons
-Fixed redstone
-Stability improvements
みなさん宜しくお願い致します。

**Comment by jdongel2004** [comment]
Redstone has lots of lag. It will need too many times..

**Comment by MCPEGamerJPatGitHub** [comment]
@jdongel2004 I'm going to try and increase performance.
