### ISSUE TITLE
Why This?

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractNetwork/Tesseract#5]
Please note that there is another Tesseract called TesseractMC that is more recent. https://GitHub.com/TesseractMC/Tesseract

**Comment by jdongel2004** [comment]
I think TesseractNetwork is better.. Plz work together!

**Comment by NFGamerMC** [comment]
Why not just make one big repo, because I have all the build data and Jenkins hosting

**Comment by jdongel2004** [comment]
Hmm.. I'll watch.

**Comment by NFGamerMC** [comment]
Why not merge, that would make it simpler for the users and for the devs!

**Comment by NFGamerMC** [comment]
By the way, are repo had auto building phars. Personally it would be better if we could merge together!

**Comment by MCPEGamerJPatGitHub** [comment]
@NFGamerMC a lot of people are privately developing Tesseract. So I would give another thought about it.

**Comment by NFGamerMC** [comment]
Someone needs to be the public one that has more than one dev.

**Comment by MCPEGamerJPatGitHub** [comment]
@NFGamerMC In terms of that, Tesseract is useless. If you want that, go to pmmp. But there you only can witness messed up code and breaking shit.

**Comment by McGrimmi** [comment]
Just join together and work together on 1 Tesseract. It's better for users etc. Please, make only one Tesseract!:)

**Comment by caspervanneck** [comment]
plz ask @Nought57

**Comment by caspervanneck** [comment]
@NFGamerMC @McGrimmi

**Comment by ISRAPIL** [comment]
Let's continue editing this repository, I believe this owner more.

**Comment by NFGamerMC** [comment]
But I have a CI and others, I just set it up so when I make a commit it will make a new Ohara and update the link in the read me on mine. Please just switch to my copy as it has more of the features and branches. Can't we work this out. You can join  and be an admin of my org. Then there will be just one. That would be better. You can copy over some of your stuff to mine two. Just make a quic pull request and I will accpet or I can just add you to the repo

**Comment by NFGamerMC** [comment]
Here, I will invite all of you to my repo

**Comment by poustmal** [comment]
2 tesseracts?

**Comment by NFGamerMC** [comment]
Just invited everyone to the new repo

**Comment by MCPEGamerJPatGitHub** [comment]
@ISRAPIL let's go :D

**Comment by Nought57** [comment]
This is a very sad thing. I and you seem to have different ideas.
It felt so from your remarks. All the build data? I don't need it.
Invite all people? It will give rise to collapse. There are many others.
I think there is no mistake in your motivation. but, I can not agree with your method.

**Comment by NFGamerMC** [comment]
I only invite people with proof and past useful commits. What I mean by build data is that I'm using CircleCI for deployment!

**Comment by Nought57** [comment]
Even if it is so, I will not move from here.
It plays an important role. This is the official view.

**Comment by NFGamerMC** [comment]
My tesseract was directly took from the repo 3 hours before it got deleted

**Comment by McGrimmi** [comment]
@Nought57 Be smart please. Move to him, or he move to you I dont care! But everybody wants only one Tesseract, not two! You should work together in team.:)

**Comment by NFGamerMC** [comment]
I want to but he doesnt
